// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRO9prKVZIr0QIe-yFs9gh8Z6RXGVZVE4',
    appId: '1:320870084669:web:4bc146049143d37ca87a54',
    messagingSenderId: '320870084669',
    projectId: 'market-search-new',
    authDomain: 'market-search-new.firebaseapp.com',
    storageBucket: 'market-search-new.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpecxG2k6FyD1-mSBDFx0lv6vHBxcZIq4',
    appId: '1:320870084669:android:b7866e177d36de8ea87a54',
    messagingSenderId: '320870084669',
    projectId: 'market-search-new',
    storageBucket: 'market-search-new.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCb4CVJXCc6OA1Cj0fvBiPW1wtiegYUwns',
    appId: '1:320870084669:ios:2769236284decf2da87a54',
    messagingSenderId: '320870084669',
    projectId: 'market-search-new',
    storageBucket: 'market-search-new.firebasestorage.app',
    iosBundleId: 'com.example.marketSearch',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCb4CVJXCc6OA1Cj0fvBiPW1wtiegYUwns',
    appId: '1:320870084669:ios:2769236284decf2da87a54',
    messagingSenderId: '320870084669',
    projectId: 'market-search-new',
    storageBucket: 'market-search-new.firebasestorage.app',
    iosBundleId: 'com.example.marketSearch',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDRO9prKVZIr0QIe-yFs9gh8Z6RXGVZVE4',
    appId: '1:320870084669:web:5ed99d4fa903d520a87a54',
    messagingSenderId: '320870084669',
    projectId: 'market-search-new',
    authDomain: 'market-search-new.firebaseapp.com',
    storageBucket: 'market-search-new.firebasestorage.app',
  );
}
